/* ============ the real 2026 schedule ============ */
/* Transcribed from released conference schedules. Games are listed once, from
   the home team's side. Weeks are 0-indexed: 0 = Sept 5 ... 12 = Nov 27/28.
   Opponents outside the 132 FBS teams in this game are simply omitted, and the
   generator fills those slots instead. */

const ALIAS={
  "Mississippi State":"Mississippi St",
  "Western Kentucky":"Western Ky",
  "Miami (FL)":"Miami",
  "Miami (OH)":"Miami (OH)",
  "Hawai'i":"Hawaii",
  "San José State":"San Jose State",
  "Appalachian State":"App State",
  "Georgia Southern":"Georgia South",
  "Coastal Carolina":"Coastal Car",
  "Western Michigan":"Western Mich",
  "Central Michigan":"Central Mich",
  "Eastern Michigan":"Eastern Mich",
  "Northern Illinois":"Northern Ill",
  "Georgia State":"Ga State",
  "Sam Houston":"Sam Houston",
  "Jacksonville State":"Jacksonville St",
  "Middle Tennessee":"Middle Tenn",
  "Florida Atlantic":"FAU",
  "Massachusetts":"UMass",
  "San Diego State":"San Diego St",
  "Washington State":"Washington St",
  "Louisiana-Monroe":"__none__",
  "UConn":"__none__",
  "UMass":"__none__",
  "Southern Miss":"__none__",
  "ULM":"__none__"
};
function realName(t){ return ALIAS[t]||t; }

/* week: 0=Sep 5, 1=Sep 12, 2=Sep 19, 3=Sep 26, 4=Oct 3, 5=Oct 10, 6=Oct 17,
   7=Oct 24, 8=Oct 31, 9=Nov 7, 10=Nov 14, 11=Nov 21, 12=Nov 27/28          */
const SCHED_2026=[
  // ---- SEC, released December 2025 ----
  {h:"Alabama",       a:"East Carolina",  w:0},
  {h:"Kentucky",      a:"Alabama",        w:1},
  {h:"Alabama",       a:"Florida State",  w:2},
  {h:"Alabama",       a:"South Carolina", w:3},
  {h:"Mississippi St",a:"Alabama",        w:4},
  {h:"Alabama",       a:"Georgia",        w:5},
  {h:"Tennessee",     a:"Alabama",        w:6},
  {h:"Alabama",       a:"Texas A&M",      w:7},
  {h:"LSU",           a:"Alabama",        w:9},
  {h:"Vanderbilt",    a:"Alabama",        w:10},
  {h:"Alabama",       a:"Auburn",         w:12},

  {h:"Utah",          a:"Arkansas",       w:1},
  {h:"Arkansas",      a:"Georgia",        w:2},
  {h:"Arkansas",      a:"Tulsa",          w:3},
  {h:"Texas A&M",     a:"Arkansas",       w:4},
  {h:"Arkansas",      a:"Tennessee",      w:5},
  {h:"Vanderbilt",    a:"Arkansas",       w:6},
  {h:"Arkansas",      a:"Missouri",       w:8},
  {h:"Auburn",        a:"Arkansas",       w:9},
  {h:"Arkansas",      a:"South Carolina", w:10},
  {h:"Texas",         a:"Arkansas",       w:11},
  {h:"Arkansas",      a:"LSU",            w:12},

  {h:"Auburn",        a:"Baylor",         w:0, neutral:true, site:"Atlanta"},
  {h:"Auburn",        a:"Florida",        w:2},
  {h:"Auburn",        a:"Vanderbilt",     w:3},
  {h:"Tennessee",     a:"Auburn",         w:4},
  {h:"Georgia",       a:"Auburn",         w:6},
  {h:"Auburn",        a:"LSU",            w:7},
  {h:"Ole Miss",      a:"Auburn",         w:8},
  {h:"Mississippi St",a:"Auburn",         w:10},

  {h:"Florida",       a:"FAU",            w:0},
  {h:"Florida",       a:"Ole Miss",       w:3},
  {h:"Missouri",      a:"Florida",        w:4},
  {h:"Florida",       a:"South Carolina", w:5},
  {h:"Texas",         a:"Florida",        w:6},
  {h:"Florida",       a:"Georgia",        w:8, neutral:true, site:"Atlanta"},
  {h:"Florida",       a:"Oklahoma",       w:9},
  {h:"Kentucky",      a:"Florida",        w:10},
  {h:"Florida",       a:"Vanderbilt",     w:11},
  {h:"Florida State", a:"Florida",        w:12},

  {h:"Georgia",       a:"Western Ky",     w:1},
  {h:"Georgia",       a:"Oklahoma",       w:3},
  {h:"Georgia",       a:"Vanderbilt",     w:4},
  {h:"Ole Miss",      a:"Georgia",        w:9},
  {h:"Georgia",       a:"Missouri",       w:10},
  {h:"South Carolina",a:"Georgia",        w:11},
  {h:"Georgia",       a:"Georgia Tech",   w:12},

  {h:"Texas A&M",     a:"Kentucky",       w:2},
  {h:"Kentucky",      a:"South Alabama",  w:3},
  {h:"South Carolina",a:"Kentucky",       w:4},
  {h:"Kentucky",      a:"LSU",            w:5},
  {h:"Oklahoma",      a:"Kentucky",       w:6},
  {h:"Kentucky",      a:"Vanderbilt",     w:7},
  {h:"Tennessee",     a:"Kentucky",       w:9},
  {h:"Missouri",      a:"Kentucky",       w:11},
  {h:"Kentucky",      a:"Louisville",     w:12},

  {h:"LSU",           a:"Clemson",        w:0},
  {h:"LSU",           a:"Louisiana Tech", w:1},
  {h:"Ole Miss",      a:"LSU",            w:2},
  {h:"LSU",           a:"Texas A&M",      w:3},
  {h:"LSU",           a:"Mississippi St", w:6},
  {h:"LSU",           a:"Texas",          w:10},
  {h:"Tennessee",     a:"LSU",            w:11},

  {h:"Ole Miss",      a:"Louisville",     w:0, neutral:true, site:"Nashville"},
  {h:"Ole Miss",      a:"Charlotte",      w:1},
  {h:"Vanderbilt",    a:"Ole Miss",       w:5},
  {h:"Ole Miss",      a:"Missouri",       w:6},
  {h:"Texas",         a:"Ole Miss",       w:7},
  {h:"Oklahoma",      a:"Ole Miss",       w:10},
  {h:"Ole Miss",      a:"Mississippi St", w:12},

  {h:"Mississippi St",a:"UL Monroe",      w:0},
  {h:"Minnesota",     a:"Mississippi St", w:1},
  {h:"South Carolina",a:"Mississippi St", w:2},
  {h:"Mississippi St",a:"Missouri",       w:3},
  {h:"Mississippi St",a:"Oklahoma",       w:7},
  {h:"Texas",         a:"Mississippi St", w:8},
  {h:"Mississippi St",a:"Vanderbilt",     w:9},

  {h:"Kansas",        a:"Missouri",       w:1},
  {h:"Missouri",      a:"Troy",           w:2},
  {h:"Missouri",      a:"Texas A&M",      w:5},
  {h:"Missouri",      a:"Texas",          w:9},
  {h:"Missouri",      a:"Oklahoma",       w:12},

  {h:"Oklahoma",      a:"UTEP",           w:0},
  {h:"Michigan",      a:"Oklahoma",       w:1},
  {h:"Oklahoma",      a:"New Mexico",     w:2},
  {h:"Oklahoma",      a:"Texas",          w:5, neutral:true, site:"Dallas"},
  {h:"Oklahoma",      a:"South Carolina", w:8},
  {h:"Oklahoma",      a:"Texas A&M",      w:11},

  {h:"South Carolina",a:"Kent State",     w:0},
  {h:"South Carolina",a:"Tennessee",      w:7},
  {h:"South Carolina",a:"Texas A&M",      w:9},
  {h:"Clemson",       a:"South Carolina", w:12},

  {h:"Georgia Tech",  a:"Tennessee",      w:1},
  {h:"Tennessee",     a:"Kennesaw State", w:2},
  {h:"Tennessee",     a:"Texas",          w:3},
  {h:"Texas A&M",     a:"Tennessee",      w:10},
  {h:"Vanderbilt",    a:"Tennessee",      w:12},

  {h:"Texas",         a:"Texas State",    w:0},
  {h:"Texas",         a:"Ohio State",     w:1},
  {h:"Texas",         a:"UTSA",           w:2},
  {h:"Texas A&M",     a:"Texas",          w:12},

  {h:"Texas A&M",     a:"Missouri State", w:0},
  {h:"Texas A&M",     a:"Arizona State",  w:1},

  {h:"Vanderbilt",    a:"Delaware",       w:1},
  {h:"Vanderbilt",    a:"NC State",       w:2},

  // ---- Big Ten, released January 2026 ----
  {h:"Illinois",      a:"UAB",            w:0},
  {h:"Illinois",      a:"Duke",           w:1},
  {h:"Ohio State",    a:"Illinois",       w:3},
  {h:"Illinois",      a:"Purdue",         w:4},
  {h:"Michigan State",a:"Illinois",       w:5},
  {h:"Illinois",      a:"Oregon",         w:7},
  {h:"Maryland",      a:"Illinois",       w:8},
  {h:"Illinois",      a:"Nebraska",       w:9},
  {h:"UCLA",          a:"Illinois",       w:10},
  {h:"Illinois",      a:"Iowa",           w:11},
  {h:"Illinois",      a:"Northwestern",   w:12},

  {h:"Indiana",       a:"North Texas",    w:0},
  {h:"Indiana",       a:"Western Ky",     w:2},
  {h:"Indiana",       a:"Northwestern",   w:3},
  {h:"Rutgers",       a:"Indiana",        w:4},
  {h:"Nebraska",      a:"Indiana",        w:5},
  {h:"Indiana",       a:"Ohio State",     w:6},
  {h:"Michigan",      a:"Indiana",        w:7},
  {h:"Indiana",       a:"Minnesota",      w:8},
  {h:"Indiana",       a:"USC",            w:10},
  {h:"Washington",    a:"Indiana",        w:11},
  {h:"Indiana",       a:"Purdue",         w:12},

  {h:"Iowa",          a:"Northern Ill",   w:0},
  {h:"Iowa",          a:"Iowa State",     w:1},
  {h:"Michigan",      a:"Iowa",           w:3},
  {h:"Iowa",          a:"Ohio State",     w:4},
  {h:"Washington",    a:"Iowa",           w:5},
  {h:"Minnesota",     a:"Iowa",           w:7},
  {h:"Iowa",          a:"Wisconsin",      w:8},
  {h:"Northwestern",  a:"Iowa",           w:9},
  {h:"Iowa",          a:"Purdue",         w:10},
  {h:"Iowa",          a:"Nebraska",       w:12},

  {h:"UConn",         a:"Maryland",       w:1},
  {h:"Maryland",      a:"Virginia Tech",  w:2},
  {h:"Maryland",      a:"UCLA",           w:3},
  {h:"Nebraska",      a:"Maryland",       w:4},
  {h:"Ohio State",    a:"Maryland",       w:5},
  {h:"Maryland",      a:"Rutgers",        w:6},
  {h:"Purdue",        a:"Maryland",       w:9},
  {h:"Maryland",      a:"Wisconsin",      w:10},
  {h:"USC",           a:"Maryland",       w:11},
  {h:"Maryland",      a:"Penn State",     w:12},

  {h:"Michigan",      a:"Western Mich",   w:0},
  {h:"Michigan",      a:"UTEP",           w:2},
  {h:"Minnesota",     a:"Michigan",       w:4},
  {h:"Michigan",      a:"Penn State",     w:6},
  {h:"Rutgers",       a:"Michigan",       w:8},
  {h:"Michigan",      a:"Michigan State", w:9},
  {h:"Oregon",        a:"Michigan",       w:10},
  {h:"Michigan",      a:"UCLA",           w:11},
  {h:"Ohio State",    a:"Michigan",       w:12},

  {h:"Michigan State",a:"Toledo",         w:0},
  {h:"Michigan State",a:"Eastern Mich",   w:1},
  {h:"Notre Dame",    a:"Michigan State", w:2},
  {h:"Michigan State",a:"Nebraska",       w:3},
  {h:"Wisconsin",     a:"Michigan State", w:4},
  {h:"Michigan State",a:"Northwestern",   w:6},
  {h:"UCLA",          a:"Michigan State", w:7},
  {h:"Michigan State",a:"Washington",     w:10},
  {h:"Michigan State",a:"Oregon",         w:11},
  {h:"Rutgers",       a:"Michigan State", w:12},

  {h:"Minnesota",     a:"Akron",          w:2},
  {h:"Washington",    a:"Minnesota",      w:3},
  {h:"Purdue",        a:"Minnesota",      w:5},
  {h:"Minnesota",     a:"UCLA",           w:9},
  {h:"Penn State",    a:"Minnesota",      w:10},
  {h:"Minnesota",     a:"Northwestern",   w:11},
  {h:"Wisconsin",     a:"Minnesota",      w:12},

  {h:"Nebraska",      a:"Ohio",           w:0},
  {h:"Nebraska",      a:"Bowling Green",  w:1},
  {h:"Oregon",        a:"Nebraska",       w:6},
  {h:"Nebraska",      a:"Washington",     w:8},
  {h:"Rutgers",       a:"Nebraska",       w:10},
  {h:"Nebraska",      a:"Ohio State",     w:11},

  {h:"Northwestern",  a:"Colorado",       w:2},
  {h:"Northwestern",  a:"Penn State",     w:4},
  {h:"Northwestern",  a:"Ball State",     w:5},
  {h:"Northwestern",  a:"Rutgers",        w:7},
  {h:"Oregon",        a:"Northwestern",   w:8},
  {h:"Ohio State",    a:"Northwestern",   w:10},

  {h:"Ohio State",    a:"Ball State",     w:0},
  {h:"Ohio State",    a:"Kent State",     w:2},
  {h:"USC",           a:"Ohio State",     w:8},
  {h:"Ohio State",    a:"Oregon",         w:9},

  {h:"Oregon",        a:"Boise State",    w:0},
  {h:"Oklahoma State",a:"Oregon",         w:1},
  {h:"USC",           a:"Oregon",         w:3},
  {h:"Oregon",        a:"UCLA",           w:5},
  {h:"Oregon",        a:"Washington",     w:12},

  {h:"Penn State",    a:"Marshall",       w:0},
  {h:"Temple",        a:"Penn State",     w:1},
  {h:"Penn State",    a:"Buffalo",        w:2},
  {h:"Penn State",    a:"Wisconsin",      w:3},
  {h:"Penn State",    a:"USC",            w:5},
  {h:"Penn State",    a:"Purdue",         w:8},
  {h:"Washington",    a:"Penn State",     w:9},
  {h:"Penn State",    a:"Rutgers",        w:11},

  {h:"Purdue",        a:"Wake Forest",    w:1},
  {h:"UCLA",          a:"Purdue",         w:2},
  {h:"Purdue",        a:"Notre Dame",     w:3},
  {h:"Purdue",        a:"Washington",     w:6},
  {h:"Purdue",        a:"Wisconsin",      w:11},

  {h:"Rutgers",       a:"UMass",          w:0},
  {h:"Boston College",a:"Rutgers",        w:1},
  {h:"Rutgers",       a:"USC",            w:2},
  {h:"Wisconsin",     a:"Rutgers",        w:9},

  {h:"California",    a:"UCLA",           w:0},
  {h:"UCLA",          a:"San Diego State",w:1},
  {h:"UCLA",          a:"Wisconsin",      w:6},
  {h:"UCLA",          a:"Nevada",         w:8},
  {h:"UCLA",          a:"USC",            w:12},

  {h:"USC",           a:"Fresno State",   w:0},
  {h:"USC",           a:"Louisiana",      w:1},
  {h:"USC",           a:"Washington",     w:4},
  {h:"Wisconsin",     a:"USC",            w:7},

  {h:"Washington",    a:"Washington State",w:0},
  {h:"Washington",    a:"Utah State",     w:1},

  {h:"Wisconsin",     a:"Notre Dame",     w:0, neutral:true, site:"Green Bay"},
  {h:"Wisconsin",     a:"Eastern Mich",   w:2}
,
  // ---- ACC, released January 2026 (nine-game transition year) ----
  {h:"Cincinnati",    a:"Boston College", w:0},
  {h:"Boston College",a:"Rutgers",        w:1},
  {h:"Boston College",a:"Virginia Tech",  w:3},
  {h:"SMU",           a:"Boston College", w:4},
  {h:"Boston College",a:"Pittsburgh",     w:6},
  {h:"Georgia Tech",  a:"Boston College", w:7},
  {h:"Duke",          a:"Boston College", w:8},
  {h:"Boston College",a:"Florida State",  w:9},
  {h:"Notre Dame",    a:"Boston College", w:10},
  {h:"Boston College",a:"Syracuse",       w:11},
  {h:"Boston College",a:"Miami",          w:12},
  {h:"California",    a:"Syracuse",       w:1},
  {h:"California",    a:"Clemson",        w:3},
  {h:"UNLV",          a:"California",     w:4},
  {h:"California",    a:"Virginia Tech",  w:5},
  {h:"California",    a:"Wake Forest",    w:6},
  {h:"SMU",           a:"California",     w:7},
  {h:"NC State",      a:"California",     w:8},
  {h:"Virginia",      a:"California",     w:10},
  {h:"California",    a:"Stanford",       w:11},
  {h:"California",    a:"Pittsburgh",     w:12},
  {h:"Clemson",       a:"Georgia South",  w:1},
  {h:"Clemson",       a:"North Carolina", w:2},
  {h:"Clemson",       a:"Miami",          w:4},
  {h:"Clemson",       a:"Virginia Tech",  w:7},
  {h:"Florida State", a:"Clemson",        w:8},
  {h:"Clemson",       a:"Syracuse",       w:9},
  {h:"Clemson",       a:"Georgia Tech",   w:10},
  {h:"Duke",          a:"Clemson",        w:11},
  {h:"Duke",          a:"Tulane",         w:0},
  {h:"Duke",          a:"Stanford",       w:2},
  {h:"Georgia Tech",  a:"Duke",           w:5},
  {h:"Duke",          a:"North Carolina", w:6},
  {h:"Virginia",      a:"Duke",           w:7},
  {h:"NC State",      a:"Duke",           w:9},
  {h:"Miami",         a:"Duke",           w:10},
  {h:"Wake Forest",   a:"Duke",           w:12},
  {h:"Florida State", a:"SMU",            w:0},
  {h:"Florida State", a:"Virginia",       w:4},
  {h:"Louisville",    a:"Florida State",  w:5},
  {h:"Miami",         a:"Florida State",  w:6},
  {h:"Pittsburgh",    a:"Florida State",  w:10},
  {h:"Florida State", a:"NC State",       w:11},
  {h:"Georgia Tech",  a:"Colorado",       w:0},
  {h:"Stanford",      a:"Georgia Tech",   w:3},
  {h:"Virginia Tech", a:"Georgia Tech",   w:6},
  {h:"Pittsburgh",    a:"Georgia Tech",   w:8},
  {h:"Georgia Tech",  a:"Louisville",     w:9},
  {h:"Georgia Tech",  a:"Wake Forest",    w:11},
  {h:"Louisville",    a:"SMU",            w:2},
  {h:"Louisville",    a:"Wake Forest",    w:3},
  {h:"NC State",      a:"Louisville",     w:4},
  {h:"Syracuse",      a:"Louisville",     w:6},
  {h:"Louisville",    a:"Stanford",       w:8},
  {h:"North Carolina",a:"Louisville",     w:10},
  {h:"Louisville",    a:"Pittsburgh",     w:11},
  {h:"Stanford",      a:"Miami",          w:0},
  {h:"Wake Forest",   a:"Miami",          w:2},
  {h:"Miami",         a:"Central Mich",   w:3},
  {h:"Miami",         a:"Pittsburgh",     w:7},
  {h:"North Carolina",a:"Miami",          w:8},
  {h:"Notre Dame",    a:"Miami",          w:9},
  {h:"Miami",         a:"Virginia Tech",  w:11},
  {h:"NC State",      a:"App State",      w:3},
  {h:"NC State",      a:"Wake Forest",    w:5},
  {h:"Stanford",      a:"NC State",       w:7},
  {h:"NC State",      a:"Syracuse",       w:10},
  {h:"North Carolina",a:"NC State",       w:12},
  {h:"North Carolina",a:"Notre Dame",     w:4},
  {h:"Pittsburgh",    a:"North Carolina", w:5},
  {h:"North Carolina",a:"Syracuse",       w:7},
  {h:"Virginia",      a:"North Carolina", w:11},
  {h:"Pittsburgh",    a:"Miami (OH)",     w:0},
  {h:"Pittsburgh",    a:"UCF",            w:1},
  {h:"Pittsburgh",    a:"Syracuse",       w:2},
  {h:"Virginia Tech", a:"Pittsburgh",     w:4},
  {h:"SMU",           a:"Missouri State", w:3},
  {h:"SMU",           a:"Virginia",       w:6},
  {h:"SMU",           a:"Syracuse",       w:8},
  {h:"SMU",           a:"Virginia Tech",  w:9},
  {h:"SMU",           a:"Wake Forest",    w:10},
  {h:"Notre Dame",    a:"SMU",            w:11},
  {h:"Stanford",      a:"SMU",            w:12},
  {h:"Stanford",      a:"Hawaii",         w:0, neutral:true},
  {h:"Wake Forest",   a:"Stanford",       w:4},
  {h:"Notre Dame",    a:"Stanford",       w:5},
  {h:"Virginia Tech", a:"Stanford",       w:10},
  {h:"Virginia",      a:"Syracuse",       w:5},
  {h:"Syracuse",      a:"Notre Dame",     w:12},
  {h:"Virginia",      a:"West Virginia",  w:2, neutral:true, site:"Charlotte"},
  {h:"Wake Forest",   a:"Virginia",       w:8},
  {h:"Virginia Tech", a:"Virginia",       w:12},
  {h:"Virginia Tech", a:"Old Dominion",   w:1},
  {h:"Maryland",      a:"Virginia Tech",  w:2},
  {h:"Wake Forest",   a:"Akron",          w:0},
  {h:"Purdue",        a:"Wake Forest",    w:1},
  // ---- Big 12, released January 2026 ----
  {h:"BYU",           a:"Arizona",        w:1},
  {h:"Arizona",       a:"Northern Ill",   w:2},
  {h:"Washington St", a:"Arizona",        w:3},
  {h:"Arizona",       a:"Cincinnati",     w:4},
  {h:"West Virginia", a:"Arizona",        w:5},
  {h:"Arizona",       a:"Iowa State",     w:7},
  {h:"Texas Tech",    a:"Arizona",        w:8},
  {h:"Arizona",       a:"TCU",            w:9},
  {h:"Arizona",       a:"Utah",           w:10},
  {h:"Kansas State",  a:"Arizona",        w:11},
  {h:"Arizona",       a:"Arizona State",  w:12},
  {h:"Arizona State", a:"Kansas",         w:2, neutral:true, site:"London"},
  {h:"Arizona State", a:"Baylor",         w:4},
  {h:"Arizona State", a:"Hawaii",         w:5},
  {h:"Texas Tech",    a:"Arizona State",  w:6},
  {h:"Arizona State", a:"Kansas State",   w:7},
  {h:"BYU",           a:"Arizona State",  w:8},
  {h:"Arizona State", a:"Colorado",       w:9},
  {h:"UCF",           a:"Arizona State",  w:10},
  {h:"Arizona State", a:"Oklahoma State", w:11},
  {h:"Baylor",        a:"Louisiana Tech", w:2},
  {h:"Baylor",        a:"Colorado",       w:3},
  {h:"Baylor",        a:"TCU",            w:6},
  {h:"Kansas",        a:"Baylor",         w:7},
  {h:"UCF",           a:"Baylor",         w:8},
  {h:"Baylor",        a:"Iowa State",     w:9},
  {h:"BYU",           a:"Baylor",         w:10},
  {h:"Baylor",        a:"Texas Tech",     w:11},
  {h:"Houston",       a:"Baylor",         w:12},
  {h:"Colorado State",a:"BYU",            w:2},
  {h:"TCU",           a:"BYU",            w:4},
  {h:"BYU",           a:"Iowa State",     w:5},
  {h:"BYU",           a:"Notre Dame",     w:6},
  {h:"UCF",           a:"BYU",            w:7},
  {h:"Utah",          a:"BYU",            w:9},
  {h:"Kansas",        a:"BYU",            w:11},
  {h:"BYU",           a:"Cincinnati",     w:12},
  {h:"Cincinnati",    a:"Miami (OH)",     w:2},
  {h:"Cincinnati",    a:"Kansas State",   w:3},
  {h:"West Virginia", a:"Cincinnati",     w:6},
  {h:"Cincinnati",    a:"Texas Tech",     w:7},
  {h:"Cincinnati",    a:"Utah",           w:8},
  {h:"Houston",       a:"Cincinnati",     w:9},
  {h:"Iowa State",    a:"Cincinnati",     w:10},
  {h:"Cincinnati",    a:"Colorado",       w:11},
  {h:"Northwestern",  a:"Colorado",       w:2},
  {h:"Colorado",      a:"Texas Tech",     w:4},
  {h:"Colorado",      a:"Utah",           w:6},
  {h:"Oklahoma State",a:"Colorado",       w:7},
  {h:"Colorado",      a:"Kansas State",   w:8},
  {h:"Colorado",      a:"Houston",        w:10},
  {h:"Colorado",      a:"UCF",            w:12},
  {h:"Houston",       a:"Oregon State",   w:0},
  {h:"Texas Tech",    a:"Houston",        w:2},
  {h:"Georgia South", a:"Houston",        w:3},
  {h:"Houston",       a:"UCF",            w:4},
  {h:"Kansas State",  a:"Houston",        w:5},
  {h:"Houston",       a:"Oklahoma State", w:6},
  {h:"Utah",          a:"Houston",        w:7},
  {h:"West Virginia", a:"Houston",        w:11},
  {h:"Iowa State",    a:"Bowling Green",  w:2},
  {h:"Iowa State",    a:"Utah",           w:3},
  {h:"Iowa State",    a:"West Virginia",  w:4},
  {h:"Iowa State",    a:"Oklahoma State", w:8},
  {h:"UCF",           a:"Iowa State",     w:11},
  {h:"Iowa State",    a:"Kansas State",   w:12},
  {h:"Kansas",        a:"Missouri",       w:1},
  {h:"Kansas",        a:"Middle Tenn",    w:4},
  {h:"Utah",          a:"Kansas",         w:5},
  {h:"Kansas State",  a:"Kansas",         w:6},
  {h:"TCU",           a:"Kansas",         w:8},
  {h:"Kansas",        a:"UCF",            w:9},
  {h:"West Virginia", a:"Kansas",         w:10},
  {h:"Oklahoma State",a:"Kansas",         w:12},
  {h:"Kansas State",  a:"Washington St",  w:1},
  {h:"Kansas State",  a:"Tulane",         w:2},
  {h:"Kansas State",  a:"Oklahoma State", w:9},
  {h:"TCU",           a:"Kansas State",   w:10},
  {h:"Tulsa",         a:"Oklahoma State", w:0},
  {h:"Oklahoma State",a:"Oregon",         w:1},
  {h:"West Virginia", a:"Oklahoma State", w:3},
  {h:"Oklahoma State",a:"UCF",            w:5},
  {h:"Oklahoma State",a:"Texas Tech",     w:10},
  {h:"TCU",           a:"Arkansas State", w:2},
  {h:"UCF",           a:"TCU",            w:3},
  {h:"TCU",           a:"West Virginia",  w:7},
  {h:"TCU",           a:"Utah",           w:11},
  {h:"Texas Tech",    a:"TCU",            w:12},
  {h:"Oregon State",  a:"Texas Tech",     w:1},
  {h:"Texas Tech",    a:"Sam Houston",    w:3},
  {h:"Texas Tech",    a:"West Virginia",  w:9},
  {h:"UCF",           a:"Ga State",       w:2},
  {h:"Utah",          a:"Utah State",     w:2},
  {h:"Utah",          a:"West Virginia",  w:12},
  {h:"West Virginia", a:"Coastal Car",    w:0},
  // ---- American, released February 2026 ----
  {h:"UAB",           a:"UL Monroe",      w:1},
  {h:"Louisiana",     a:"UAB",            w:2},
  {h:"UAB",           a:"Navy",           w:3},
  {h:"Memphis",       a:"UAB",            w:5},
  {h:"UAB",           a:"East Carolina",  w:6},
  {h:"South Florida", a:"UAB",            w:8},
  {h:"UAB",           a:"Charlotte",      w:9},
  {h:"Temple",        a:"UAB",            w:10},
  {h:"UAB",           a:"UTSA",           w:11},
  {h:"North Texas",   a:"UAB",            w:12},
  {h:"Army",          a:"South Florida",  w:1},
  {h:"Temple",        a:"Army",           w:3},
  {h:"Louisiana Tech",a:"Army",           w:4},
  {h:"Army",          a:"Tulane",         w:5},
  {h:"Army",          a:"FAU",            w:6},
  {h:"Tulsa",         a:"Army",           w:7},
  {h:"Memphis",       a:"Army",           w:8},
  {h:"Army",          a:"Air Force",      w:9},
  {h:"Army",          a:"East Carolina",  w:11},
  {h:"Rice",          a:"Army",           w:12},
  {h:"Ole Miss",      a:"Charlotte",      w:1},
  {h:"App State",     a:"Charlotte",      w:2},
  {h:"Charlotte",     a:"Louisiana",      w:3},
  {h:"Charlotte",     a:"Memphis",        w:4},
  {h:"North Texas",   a:"Charlotte",      w:5},
  {h:"Temple",        a:"Charlotte",      w:6},
  {h:"Charlotte",     a:"Tulane",         w:8},
  {h:"Charlotte",     a:"East Carolina",  w:10},
  {h:"Tulsa",         a:"Charlotte",      w:11},
  {h:"Charlotte",     a:"Navy",           w:12},
  {h:"Alabama",       a:"East Carolina",  w:0},
  {h:"East Carolina", a:"App State",      w:1},
  {h:"Old Dominion",  a:"East Carolina",  w:2},
  {h:"East Carolina", a:"Rice",           w:5},
  {h:"East Carolina", a:"Temple",         w:8},
  {h:"East Carolina", a:"South Florida",  w:9},
  {h:"East Carolina", a:"FAU",            w:12},
  {h:"Florida",       a:"FAU",            w:0},
  {h:"FAU",           a:"Navy",           w:1},
  {h:"FAU",           a:"FIU",            w:2},
  {h:"UL Monroe",     a:"FAU",            w:3},
  {h:"FAU",           a:"Rice",           w:7},
  {h:"North Texas",   a:"FAU",            w:8},
  {h:"FAU",           a:"UTSA",           w:9},
  {h:"Tulsa",         a:"FAU",            w:10},
  {h:"FAU",           a:"South Florida",  w:11},
  {h:"UNLV",          a:"Memphis",        w:0},
  {h:"Memphis",       a:"Arkansas State", w:0},
  {h:"Boise State",   a:"Memphis",        w:1},
  {h:"Tulane",        a:"Memphis",        w:6},
  {h:"Memphis",       a:"East Carolina",  w:7},
  {h:"South Florida", a:"Memphis",        w:10},
  {h:"Navy",          a:"Memphis",        w:11},
  {h:"Memphis",       a:"Temple",         w:12},
  {h:"Air Force",     a:"Navy",           w:4},
  {h:"Navy",          a:"Tulsa",          w:5},
  {h:"UTSA",          a:"Navy",           w:6},
  {h:"Navy",          a:"North Texas",    w:7},
  {h:"Navy",          a:"Notre Dame",     w:8, neutral:true, site:"Foxborough"},
  {h:"Navy",          a:"Temple",         w:9},
  {h:"Indiana",       a:"North Texas",    w:0},
  {h:"North Texas",   a:"UNLV",           w:1},
  {h:"Texas State",   a:"North Texas",    w:2},
  {h:"Tulsa",         a:"North Texas",    w:4},
  {h:"North Texas",   a:"Rice",           w:9},
  {h:"UTSA",          a:"North Texas",    w:10},
  {h:"Tulane",        a:"North Texas",    w:11},
  {h:"Notre Dame",    a:"Rice",           w:1},
  {h:"Rice",          a:"Western Mich",   w:2},
  {h:"Fresno State",  a:"Rice",           w:3},
  {h:"Rice",          a:"UTSA",           w:4},
  {h:"Rice",          a:"Tulsa",          w:6},
  {h:"Rice",          a:"Tulane",         w:10},
  {h:"Temple",        a:"Rice",           w:11},
  {h:"South Florida", a:"FIU",            w:0},
  {h:"Bowling Green", a:"South Florida",  w:3},
  {h:"South Florida", a:"Temple",         w:4},
  {h:"UTSA",          a:"South Florida",  w:5},
  {h:"South Florida", a:"Kent State",     w:6},
  {h:"South Florida", a:"Tulane",         w:12},
  {h:"Temple",        a:"Penn State",     w:1},
  {h:"Toledo",        a:"Temple",         w:2},
  {h:"Temple",        a:"UConn",          w:5},
  {h:"UTSA",          a:"Texas State",    w:1},
  {h:"Texas",         a:"UTSA",           w:2},
  {h:"UTSA",          a:"Colorado State", w:3},
  {h:"Tulane",        a:"UTSA",           w:7},
  {h:"UTSA",          a:"Tulsa",          w:12},
  {h:"Duke",          a:"Tulane",         w:0},
  {h:"Tulane",        a:"South Alabama",  w:1},
  {h:"Kansas State",  a:"Tulane",         w:2},
  {h:"Tulane",        a:"Southern Miss",  w:3},
  {h:"Tulane",        a:"Tulsa",          w:9},
  {h:"Tulsa",         a:"Oklahoma State", w:0},
  {h:"Sam Houston",   a:"Tulsa",          w:1},
  {h:"Arkansas",      a:"Tulsa",          w:3},
  // ---- Mountain West, released March 2026 ----
  {h:"UNLV",          a:"Memphis",        w:0},
  {h:"Hawaii",        a:"UNLV",           w:0},
  {h:"Nevada",        a:"Western Ky",     w:0},
  {h:"New Mexico",    a:"Central Mich",   w:0},
  {h:"Iowa",          a:"Northern Ill",   w:0},
  {h:"Colorado State",a:"Wyoming",        w:0},
  {h:"Hawaii",        a:"New Mexico St",  w:1},
  {h:"North Texas",   a:"UNLV",           w:1},
  {h:"Michigan",      a:"UTEP",           w:2},
  {h:"Middle Tenn",   a:"Nevada",         w:2},
  {h:"Arizona",       a:"Northern Ill",   w:2},
  {h:"San Jose State",a:"Fresno State",   w:2},
  {h:"Central Mich",  a:"Wyoming",        w:2},
  {h:"Nevada",        a:"Air Force",      w:3},
  {h:"Wyoming",       a:"Hawaii",         w:3},
  {h:"New Mexico St", a:"New Mexico",     w:3},
  {h:"Ga State",      a:"Northern Ill",   w:3},
  {h:"Akron",         a:"UNLV",           w:3},
  {h:"UTEP",          a:"Oregon State",   w:3},
  {h:"Air Force",     a:"Navy",           w:4},
  {h:"Hawaii",        a:"San Jose State", w:4},
  {h:"New Mexico",    a:"UTEP",           w:4},
  {h:"UNLV",          a:"California",     w:4},
  {h:"Northern Ill",  a:"Air Force",      w:5},
  {h:"Arizona State", a:"Hawaii",         w:5},
  {h:"UTEP",          a:"Nevada",         w:5},
  {h:"San Jose State",a:"Wyoming",        w:5},
  {h:"Hawaii",        a:"New Mexico",     w:6},
  {h:"Wyoming",       a:"Northern Ill",   w:6},
  {h:"UTEP",          a:"San Jose State", w:6},
  {h:"Air Force",     a:"UNLV",           w:6},
  {h:"Wyoming",       a:"Air Force",      w:7},
  {h:"Northern Ill",  a:"Hawaii",         w:7},
  {h:"Nevada",        a:"San Jose State", w:7},
  {h:"Air Force",     a:"UConn",          w:8},
  {h:"UCLA",          a:"Nevada",         w:8},
  {h:"San Jose State",a:"New Mexico",     w:8},
  {h:"UNLV",          a:"Northern Ill",   w:8},
  {h:"Army",          a:"Air Force",      w:9},
  {h:"UTEP",          a:"Hawaii",         w:9},
  {h:"Nevada",        a:"New Mexico",     w:9},
  {h:"San Jose State",a:"Northern Ill",   w:9},
  {h:"UNLV",          a:"Wyoming",        w:9},
  {h:"Northern Ill",  a:"Nevada",         w:10},
  {h:"Air Force",     a:"San Jose State", w:10},
  {h:"New Mexico",    a:"UNLV",           w:10},
  {h:"UTEP",          a:"Wyoming",        w:10},
  {h:"Nevada",        a:"Hawaii",         w:11},
  {h:"Wyoming",       a:"New Mexico",     w:11},
  {h:"San Jose State",a:"UNLV",           w:11},
  {h:"Air Force",     a:"UTEP",           w:11},
  {h:"New Mexico",    a:"Air Force",      w:12},
  {h:"UNLV",          a:"Nevada",         w:12},
  {h:"Northern Ill",  a:"UTEP",           w:12},
  {h:"Wyoming",       a:"UConn",          w:12},
  // ---- Sun Belt, released March 2026 ----
  {h:"Memphis",       a:"Arkansas State", w:0},
  {h:"West Virginia", a:"Coastal Car",    w:0},
  {h:"James Madison", a:"Liberty",        w:0},
  {h:"Mississippi St",a:"UL Monroe",      w:0},
  {h:"Penn State",    a:"Marshall",       w:0},
  {h:"Troy",          a:"Sam Houston",    w:0},
  {h:"East Carolina", a:"App State",      w:1},
  {h:"Clemson",       a:"Georgia South",  w:1},
  {h:"Kennesaw State",a:"Ga State",       w:1},
  {h:"USC",           a:"Louisiana",      w:1},
  {h:"LSU",           a:"Louisiana Tech", w:1},
  {h:"Marshall",      a:"Middle Tenn",    w:1},
  {h:"Virginia Tech", a:"Old Dominion",   w:1},
  {h:"Tulane",        a:"South Alabama",  w:1},
  {h:"Auburn",        a:"Southern Miss",  w:1},
  {h:"App State",     a:"Charlotte",      w:2},
  {h:"TCU",           a:"Arkansas State", w:2},
  {h:"Delaware",      a:"Coastal Car",    w:2},
  {h:"Jacksonville St",a:"Georgia South", w:2},
  {h:"UCF",           a:"Ga State",       w:2},
  {h:"San Diego St",  a:"James Madison",  w:2},
  {h:"Louisiana",     a:"UAB",            w:2},
  {h:"Baylor",        a:"Louisiana Tech", w:2},
  {h:"Missouri State",a:"Marshall",       w:2},
  {h:"Old Dominion",  a:"East Carolina",  w:2},
  {h:"South Alabama", a:"Ohio",           w:2},
  {h:"Missouri",      a:"Troy",           w:2},
  {h:"Coastal Car",   a:"Liberty",        w:3},
  {h:"NC State",      a:"App State",      w:3},
  {h:"Arkansas State",a:"Kennesaw State", w:3},
  {h:"Georgia South", a:"Houston",        w:3},
  {h:"Ga State",      a:"Northern Ill",   w:3},
  {h:"Charlotte",     a:"Louisiana",      w:3},
  {h:"UL Monroe",     a:"FAU",            w:3},
  {h:"Old Dominion",  a:"James Madison",  w:3},
  {h:"Kentucky",      a:"South Alabama",  w:3},
  {h:"Tulane",        a:"Southern Miss",  w:3},
  {h:"Utah State",    a:"Troy",           w:3},
  {h:"Coastal Car",   a:"Georgia South",  w:4},
  {h:"Ga State",      a:"Old Dominion",   w:4},
  {h:"James Madison", a:"Marshall",       w:4},
  {h:"Louisiana",     a:"Arkansas State", w:4},
  {h:"Louisiana Tech",a:"Army",           w:4},
  {h:"South Alabama", a:"UL Monroe",      w:4},
  {h:"Troy",          a:"Southern Miss",  w:5},
  {h:"Arkansas State",a:"South Alabama",  w:5},
  {h:"App State",     a:"Old Dominion",   w:5},
  {h:"Georgia South", a:"James Madison",  w:5},
  {h:"Louisiana Tech",a:"Louisiana",      w:5},
  {h:"Marshall",      a:"Coastal Car",    w:5},
  {h:"Old Dominion",  a:"Georgia South",  w:6},
  {h:"Coastal Car",   a:"App State",      w:6},
  {h:"James Madison", a:"Ga State",       w:6},
  {h:"Louisiana",     a:"Troy",           w:6},
  {h:"UL Monroe",     a:"Louisiana Tech", w:6},
  {h:"Southern Miss", a:"Arkansas State", w:6},
  {h:"Marshall",      a:"South Alabama",  w:7},
  {h:"App State",     a:"James Madison",  w:7},
  {h:"Arkansas State",a:"Ga State",       w:7},
  {h:"Louisiana Tech",a:"Old Dominion",   w:7},
  {h:"Southern Miss", a:"Louisiana",      w:7},
  {h:"Troy",          a:"UL Monroe",      w:7},
  {h:"James Madison", a:"Troy",           w:8},
  {h:"Georgia South", a:"App State",      w:8},
  {h:"Ga State",      a:"Coastal Car",    w:8},
  {h:"UL Monroe",     a:"Southern Miss",  w:8},
  {h:"Old Dominion",  a:"Marshall",       w:8},
  {h:"South Alabama", a:"Louisiana Tech", w:8},
  {h:"Southern Miss", a:"James Madison",  w:9},
  {h:"App State",     a:"Ga State",       w:9},
  {h:"Arkansas State",a:"UL Monroe",      w:9},
  {h:"Coastal Car",   a:"Old Dominion",   w:9},
  {h:"Georgia South", a:"Marshall",       w:9},
  {h:"Louisiana",     a:"South Alabama",  w:9},
  {h:"Troy",          a:"Louisiana Tech", w:9},
  {h:"UL Monroe",     a:"Louisiana",      w:10},
  {h:"Coastal Car",   a:"Arkansas State", w:10},
  {h:"Ga State",      a:"Georgia South",  w:10},
  {h:"Louisiana Tech",a:"Southern Miss",  w:10},
  {h:"Marshall",      a:"App State",      w:10},
  {h:"South Alabama", a:"Troy",           w:10},
  {h:"Louisiana Tech",a:"Arkansas State", w:11},
  {h:"App State",     a:"UL Monroe",      w:11},
  {h:"Louisiana",     a:"Coastal Car",    w:11},
  {h:"Marshall",      a:"Ga State",       w:11},
  {h:"Southern Miss", a:"South Alabama",  w:11},
  {h:"Troy",          a:"Georgia South",  w:11},
  {h:"Arkansas State",a:"Troy",           w:12},
  {h:"Georgia South", a:"Louisiana Tech", w:12},
  {h:"Ga State",      a:"Louisiana",      w:12},
  {h:"James Madison", a:"Coastal Car",    w:12},
  {h:"UL Monroe",     a:"Marshall",       w:12},
  {h:"Old Dominion",  a:"Southern Miss",  w:12},
  {h:"South Alabama", a:"App State",      w:12},
  // ---- MAC, released March 2026 ----
  {h:"Wake Forest",   a:"Akron",          w:0},
  {h:"Ohio State",    a:"Ball State",     w:0},
  {h:"New Mexico",    a:"Central Mich",   w:0},
  {h:"South Carolina",a:"Kent State",     w:0},
  {h:"Pittsburgh",    a:"Miami (OH)",     w:0},
  {h:"Nebraska",      a:"Ohio",           w:0},
  {h:"Michigan State",a:"Toledo",         w:0},
  {h:"Michigan",      a:"Western Mich",   w:0},
  {h:"Nebraska",      a:"Bowling Green",  w:1},
  {h:"FIU",           a:"Buffalo",        w:1},
  {h:"Michigan State",a:"Eastern Mich",   w:1},
  {h:"Ohio",          a:"Jacksonville St",w:1},
  {h:"Minnesota",     a:"Akron",          w:2},
  {h:"Liberty",       a:"Ball State",     w:2},
  {h:"Iowa State",    a:"Bowling Green",  w:2},
  {h:"Penn State",    a:"Buffalo",        w:2},
  {h:"Central Mich",  a:"Wyoming",        w:2},
  {h:"Wisconsin",     a:"Eastern Mich",   w:2},
  {h:"Ohio State",    a:"Kent State",     w:2},
  {h:"Cincinnati",    a:"Miami (OH)",     w:2},
  {h:"South Alabama", a:"Ohio",           w:2},
  {h:"Toledo",        a:"Temple",         w:2},
  {h:"Rice",          a:"Western Mich",   w:2},
  {h:"Akron",         a:"UNLV",           w:3},
  {h:"Kent State",    a:"Ball State",     w:3},
  {h:"Bowling Green", a:"South Florida",  w:3},
  {h:"Miami",         a:"Central Mich",   w:3},
  {h:"Toledo",        a:"San Diego St",   w:3},
  {h:"Western Mich",  a:"Boise State",    w:3},
  {h:"Central Mich",  a:"Akron",          w:4},
  {h:"Ball State",    a:"Toledo",         w:4},
  {h:"Miami (OH)",    a:"Bowling Green",  w:4},
  {h:"Buffalo",       a:"Western Mich",   w:4},
  {h:"Kent State",    a:"Ohio",           w:4},
  {h:"Akron",         a:"Eastern Mich",   w:5},
  {h:"Northwestern",  a:"Ball State",     w:5},
  {h:"Toledo",        a:"Buffalo",        w:5},
  {h:"Ohio",          a:"Central Mich",   w:5},
  {h:"Western Mich",  a:"Kent State",     w:5},
  {h:"Miami (OH)",    a:"Akron",          w:6},
  {h:"Bowling Green", a:"Ball State",     w:6},
  {h:"Buffalo",       a:"Miami (OH)",     w:6},
  {h:"Central Mich",  a:"Western Mich",   w:6},
  {h:"Eastern Mich",  a:"Toledo",         w:6},
  {h:"South Florida", a:"Kent State",     w:6},
  {h:"Kent State",    a:"Akron",          w:7},
  {h:"Buffalo",       a:"Bowling Green",  w:7},
  {h:"Central Mich",  a:"Miami (OH)",     w:7},
  {h:"Ohio",          a:"Eastern Mich",   w:7},
  {h:"Toledo",        a:"Western Mich",   w:7},
  {h:"Western Mich",  a:"Bowling Green",  w:8},
  {h:"Akron",         a:"Ohio",           w:9},
  {h:"Miami (OH)",    a:"Buffalo",        w:9},
  {h:"Eastern Mich",  a:"Central Mich",   w:9},
  {h:"Akron",         a:"Western Mich",   w:10},
  {h:"Bowling Green", a:"Kent State",     w:10},
  {h:"Miami (OH)",    a:"Ohio",           w:10},
  {h:"Ball State",    a:"Buffalo",        w:10},
  {h:"Ohio",          a:"Ball State",     w:11},
  {h:"Western Mich",  a:"Eastern Mich",   w:11},
  {h:"Kent State",    a:"Miami (OH)",     w:11},
  {h:"Toledo",        a:"Bowling Green",  w:11},
  {h:"Buffalo",       a:"Central Mich",   w:11},
  {h:"Eastern Mich",  a:"Kent State",     w:12},
  {h:"Western Mich",  a:"Miami (OH)",     w:12},
  {h:"Akron",         a:"Buffalo",        w:12},
  {h:"Ohio",          a:"Toledo",         w:12},
  {h:"Ball State",    a:"Central Mich",   w:12},
  // ---- Pac-12, released February 2026 ----
  // Seven-game round robin; the pairings are fixed by format, the ordering
  // within the conference window is approximate.
  {h:"Washington St",  a:"Boise State",    w:4},
  {h:"Utah State",     a:"Colorado State", w:4},
  {h:"Texas State",    a:"Fresno State",   w:4},
  {h:"San Diego St",   a:"Oregon State",   w:4},
  {h:"Boise State",    a:"Utah State",     w:5},
  {h:"Washington St",  a:"Texas State",    w:5},
  {h:"Colorado State", a:"San Diego St",   w:5},
  {h:"Fresno State",   a:"Oregon State",   w:5},
  {h:"Texas State",    a:"Boise State",    w:6},
  {h:"San Diego St",   a:"Utah State",     w:6},
  {h:"Oregon State",   a:"Washington St",  w:6},
  {h:"Fresno State",   a:"Colorado State", w:6},
  {h:"Boise State",    a:"San Diego St",   w:7},
  {h:"Texas State",    a:"Oregon State",   w:7},
  {h:"Utah State",     a:"Fresno State",   w:7},
  {h:"Washington St",  a:"Colorado State", w:7},
  {h:"Oregon State",   a:"Boise State",    w:8},
  {h:"Fresno State",   a:"San Diego St",   w:8},
  {h:"Colorado State", a:"Texas State",    w:8},
  {h:"Washington St",  a:"Utah State",     w:8},
  {h:"Boise State",    a:"Fresno State",   w:9},
  {h:"Oregon State",   a:"Colorado State", w:9},
  {h:"San Diego St",   a:"Washington St",  w:9},
  {h:"Texas State",    a:"Utah State",     w:9},
  {h:"Colorado State", a:"Boise State",    w:10},
  {h:"Washington St",  a:"Fresno State",   w:10},
  {h:"Utah State",     a:"Oregon State",   w:10},
  {h:"Texas State",    a:"San Diego St",   w:10},
  {h:"USC",            a:"Fresno State",   w:0},
  {h:"Houston",        a:"Oregon State",   w:0},
  {h:"Texas",          a:"Texas State",    w:0},
  {h:"Oregon",         a:"Boise State",    w:0},
  {h:"Colorado State", a:"Wyoming",        w:0},
  {h:"Washington",     a:"Washington St",  w:0},
  {h:"Boise State",    a:"Memphis",        w:1},
  {h:"Colorado State", a:"BYU",            w:1},
  {h:"Oregon State",   a:"Texas Tech",     w:1},
  {h:"Washington",     a:"Utah State",     w:1},
  {h:"UCLA",           a:"San Diego St",   w:1},
  {h:"San Diego St",   a:"James Madison",  w:2},
  {h:"San Jose State", a:"Fresno State",   w:2},
  {h:"UTSA",           a:"Colorado State", w:3},
  {h:"Utah State",     a:"Troy",           w:3},
  {h:"Toledo",         a:"San Diego St",   w:3},
  {h:"Western Mich",   a:"Boise State",    w:3},
  {h:"Utah State",     a:"Boise State",    w:12},
  {h:"Colorado State", a:"Texas State",    w:12},
  {h:"Fresno State",   a:"San Diego St",   w:12},
  {h:"Washington St",  a:"Oregon State",   w:12},
  // ---- Conference USA, revised April 2026 (Louisiana Tech to the Sun Belt) ----
  {h:"Vanderbilt",    a:"Delaware",       w:1},
  {h:"South Florida", a:"FIU",            w:0},
  {h:"Jacksonville St",a:"Georgia South", w:2},
  {h:"Tennessee",     a:"Kennesaw State", w:2},
  {h:"Kansas",        a:"Middle Tenn",    w:4},
  {h:"Texas A&M",     a:"Missouri State", w:0},
  {h:"Florida State", a:"New Mexico St",  w:0},
  {h:"Texas Tech",    a:"Sam Houston",    w:3},
  {h:"Georgia",       a:"Western Ky",     w:1},
  {h:"New Mexico St", a:"Western Ky",     w:4},
  {h:"Delaware",      a:"Liberty",        w:4},
  {h:"FIU",           a:"New Mexico St",  w:5},
  {h:"Kennesaw State",a:"Jacksonville St",w:5},
  {h:"Liberty",       a:"Sam Houston",    w:5},
  {h:"Western Ky",    a:"Missouri State", w:5},
  {h:"Middle Tenn",   a:"Delaware",       w:6},
  {h:"Jacksonville St",a:"FIU",           w:6},
  {h:"Missouri State",a:"Kennesaw State", w:6}];

